apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: aransh/echo
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: echo-db-secret
          - configMapRef:
              name: config-echo
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        