apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: echo-ingress
spec:
  rules:
    - host: dev.echoday3.tk
      http: 
        paths:
          - backend:
              serviceName: echo
              servicePort: 80
  tls:
    - hosts:
      - dev.echoday3.tk
      secretName: letsencrypt-prod