apiVersion: v1
kind: ConfigMap
metadata:
    name: echo-config-echo
data:
    PORT: "3000"
    LOGLEVEL: "{{ .Values.loglevel }}"
    {{ if eq .Values.db.enabled true }}
    PERSIST: "true"
    {{ end }}
    DBNAME: "{{ .Values.db.dbname }}"