replicas: 2

domain: staging.echoday3.tk
service: ClusterIP

tls:
  enabled: false
  issuerName: letsencrypt-prod

loglevel: info

db:
  enabled: true
  dbname: echo-staging
  collection: echos
  dburl: bW9uZ29kYnVybDogbW9uZ29kYjovL2FyYW5zaDpwYXNzQG1vbmdvZGItMC5tb25nb2RiLmRlZmF1bHQsbW9uZ29kYi0xLm1vbmdvZGIuZGVmYXVsdCxtb25nb2RiLTIubW9uZ29kYi5kZWZhdWx0OjI3MDE3L2VjaG8/YXV0aFNvdXJjZT1hZG1pbgo=
  masterHost: mongodb-0.mongodb
  username: YXJhbnNoCg==
  password: cGFzcwo=

purging:
  enabled: true
  schedule: "0 0 * * *"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

logging:
  enabled: true